### ISSUE TITLE
Map Depth Data Unavailable toast remains on screen

### ISSUE THREAD

**Issue by ZackLyon** [mbari-org/dash5#415]
**Describe the bug**
The toast message notifying the user that depth data is unavailable remains on screen indefinitely

**To Reproduce**
1. Go to staging
2. Click on a vehicle tab
3. Click on the depth data tab at the bottom
4. See toast come up and remain there

**Expected behavior**
The toast should only come up once and stay briefly

**Screenshots**
<img width="1280" alt="Image" src="https://github.com/user-attachments/assets/285242e7-096d-4b04-9dfa-e78dfedafdba" />

**Comment by ksalamy** [comment]
These should be fixed in the new #418 (or reverted #419). The GoogleMapApiKey and Elevation services are now working on dash5-staging. The depth data also removes the toast issue as a restult.

**Comment by ZackLyon** [comment]
@ksalamy - Did you fix the code for the toast so that it only comes up once? Or are you saying that as long as there is depth data, the toast doesn't come up?

**Comment by ksalamy** [comment]
The latter.

_______________
Karen A. Salamy
Associate SW Engineer, MBARI
P 831.775.1820,   F 831.775.1620
[https://www.mbari.org/signature/MBARI-Email-Signature-logo.gif]
[https://www.mbari.org/signature/VertBar.jpg]
Monterey Bay Aquarium Research Institute (MBARI)
7700 Sandholdt Road, Moss Landing CA 95039
www.mbari.org<http://www.mbari.org/>
Advancing marine science and engineering to understand our changing ocean.


"If we knew what it was we were doing, it would not be called research, would it?" - Albert Einstein (1879-1955)

P Please consider the environment before printing this e-mail.

________________________________

**Comment by ZackLyon** [comment]
I'm going to open this back up since there's still an issue with the toast being persistent when there's no depth data, instead of informing the user, then disappearing.
